"""Agregar columna cantidad a la tabla papelera

Revision ID: 07b1380d351f
Revises: 
Create Date: 2024-09-26 01:23:02.251943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b1380d351f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('papelera', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.Integer(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papelera', schema=None) as batch_op:
        batch_op.drop_column('cantidad')

    # ### end Alembic commands ###
