"""Recreate migration for adding codigo field

Revision ID: 3772a203fb6d
Revises: 
Create Date: 2024-09-12 03:05:45.581001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3772a203fb6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_cotizacion')
    with op.batch_alter_table('cotizacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mensaje_david', sa.String(length=255), nullable=True))
        batch_op.alter_column('codigo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotizacion', schema=None) as batch_op:
        batch_op.alter_column('codigo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('mensaje_david')

    op.create_table('_alembic_tmp_cotizacion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('componente', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cotizacion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('recordatorio', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('respondido', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('numero_serie', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mostrar_recordatorio', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('codigo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='_alembic_tmp_cotizacion_pkey')
    )
    # ### end Alembic commands ###
