"""Agregar campo cancelado a Cotizacion

Revision ID: 9dc1030aabaf
Revises: 3772a203fb6d
Create Date: 2024-09-25 00:53:35.746990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc1030aabaf'
down_revision = '3772a203fb6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotizacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelado', sa.Boolean(), nullable=True))
        batch_op.alter_column('codigo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotizacion', schema=None) as batch_op:
        batch_op.alter_column('codigo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('cancelado')

    # ### end Alembic commands ###
