"""Agregar campos solicitante y área de equipo

Revision ID: f1453cf5ffa6
Revises: ddadc3e98302
Create Date: 2024-10-14 22:34:45.925380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1453cf5ffa6'
down_revision = 'ddadc3e98302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotizacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solicitante_nombre', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('solicitante_numero', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('solicitante_correo', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotizacion', schema=None) as batch_op:
        batch_op.drop_column('solicitante_correo')
        batch_op.drop_column('solicitante_numero')
        batch_op.drop_column('solicitante_nombre')

    # ### end Alembic commands ###
